### ISSUE TITLE
Error when adding camera under 0.6.5 Release

### ISSUE THREAD

**Issue by mikedrews** [xannor/ha_reolink_rest#24]
When I updated to .0.6.5 all the cameras previously installed were in error.  I deleted the integration and started from scratch.

Received the following errors when adding a single RLC-811A camera which worked with release 0.6.4
Logger: homeassistant.config_entries
Source: config_entries.py:1067
First occurred: 6:45:25 PM (1 occurrences)
Last logged: 6:45:25 PM

Config entry 'Lake View' for reolink_rest integration not ready yet: 'int' object has no attribute 'value'; Retrying in background

This error originated from a custom integration.

Logger: custom_components.reolink_rest
Source: util/dt.py:118
Integration: Reolink IP Device (documentation, issues)
First occurred: 6:44:57 PM (8 occurrences)
Last logged: 6:46:41 PM

Unexpected error fetching reolink_rest-192.168.2.88 data: 'int' object has no attribute 'value'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/reolink_rest/__init__.py", line 81, in _update_data
    return await entity_data.async_update()
  File "/config/custom_components/reolink_rest/entity.py", line 453, in async_update
    result = await self._execute_commands(commands, command_channel=command_channel)
  File "/config/custom_components/reolink_rest/entity.py", line 309, in _execute_commands
    self._processes_responses(response)
  File "/config/custom_components/reolink_rest/entity.py", line 261, in _processes_responses
    self.time_difference = dt.utcnow() - dt.as_utc(time)
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 118, in as_utc
    return dattim.astimezone(UTC)
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/commands/system.py", line 81, in utcoffset
    (start, end) = self._get_start_end(__dt.year)
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/commands/system.py", line 71, in _get_start_end
    year, (self._start.to_datetime(year), self._end.to_datetime(year))
  File "/usr/local/lib/python3.10/site-packages/async_reolink/api/system/typings.py", line 71, in to_datetime
    delta += timedelta(days=self.weekday.value - WeekDays.MONDAY.value)
AttributeError: 'int' object has no attribute 'value'

**Comment by xannor** [comment]
I remove that release, I rushed it out and shouldn't have, I know what I need to fix but I wont have time to do it tonight, and proplery test. please "downgrade" to v0.6.4 (d6d323d) until I can make a 0.6.6, which may take a few days due to limited time.

**Comment by kingy444** [comment]
@mikedrews if you cant work it out (I had the same issue) steps below i followed to 'downgrade' below as version wasnt availble in HACS - could only select 'main'

1. Download https://github.com/xannor/ha_reolink_rest/archive/d6d323d2702ec2eb1a835895c594d5d5f920024e.zip
2. Exctract the zip
3. copy the reolink_rest directory over the top of the existing one in 'custom_components' (samba share is easiest way)
4. restart HA

**Comment by xannor** [comment]
I have a new, better tested, version (v0.6.6), let me know if this works better.

**Comment by mikedrews** [comment]
All the cameras are good with the exception of PTZ control for certain models.
The following is a RLC-511W that has a panel for "Configuration" as shown.  I have another RLC-511W camera with the same firmware that is missing the Configuration panel.
![HA Reolink Workshop Cam](https://user-images.githubusercontent.com/110789962/191116145-24bfb8b6-7df0-4764-9066-33cdb267ed9a.jpg)
![HA Reolink Garage Side Door Cam](https://user-images.githubusercontent.com/110789962/191116217-9ed4ecdc-5b31-4f5c-8e75-336f47d30795.jpg)

Also, the following E1 Zoom only shows a Zoom function in the Configuration panel.  There is no PTZ control within any of the feeds.
![HA Reolink E1Zoom Cam](https://user-images.githubusercontent.com/110789962/191116890-3cfc4fd8-fb64-4e1b-9690-9631b7ab3fab.jpg)

**Comment by xannor** [comment]
I only implemented autofocus, zoom, and focus, as that is all my 511W supports, so all I can test with. I use the "abilities" of the user as reported by the camera to enable the controls, so my best guess would be that the user loggin into the one that doesn show the controlls does not have permission to use them.

**Comment by xannor** [comment]
To help with the E1 and 511 issue if you could add debug logging to your setup and provide the debug entries as per this page https://github.com/xannor/ha_reolink_rest/wiki/Logs it would really help.

**Comment by mikedrews** [comment]
You were correct with respect to the user access for the E1 Zoom.  A regular user does not have access to pan and tilt features.
The incomplete Configuration panel on one of the 511W's has magically appeared.  So all 3 of my 511W's are good.  My 2 RLC-811A's appear to be good.

I deleted the E1 Zoom and before I readded it with admin access I noticed this in the logs (debug enabled).

2022-09-20 09:08:36.884 WARNING (MainThread) [custom_components.reolink_rest.push] Got disconnected on attempt to unsubscribe, assuming invalid subscription

Here is the log when trying to add the E1 Zoom with admin access, this repeats 4 or 5 times;
(the camera is added to the your "Reolink IP Device" panel list but is in error)

2022-09-20 09:18:17.016 ERROR (MainThread) [custom_components.reolink_rest] Unexpected error fetching reolink_rest-192.168.2.198 data: invalid response
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
return await self.update_method()
File "/config/custom_components/reolink_rest/__init__.py", line 82, in _update_data
return await entity_data.async_update()
File "/config/custom_components/reolink_rest/entity.py", line 436, in async_update
raise reoresp
File "/config/custom_components/reolink_rest/entity.py", line 422, in async_update
self.abilities = await self.client.get_ability(
File "/usr/local/lib/python3.10/site-packages/async_reolink/api/system/__init__.py", line 65, in get_ability
async for response in self._execute(
File "/usr/local/lib/python3.10/site-packages/async_reolink/rest/connection.py", line 350, in __execute
raise errors.ReolinkResponseError(
async_reolink.api.errors.ReolinkResponseError: invalid response

When I add the E1 Zoom using a regular user account defined on the camera I get no errors and it adds fine.
Here is something else I noticed.  In order to test the admin vs regular user E1 features I installed the Reolink app on an older  phone. When I went through the same process of trying to add the E1 with admin access the app just hung there.  I canceled and tried again and it worked.

By the way, I wanted to thank you for all your efforts in committing to getting this integration to work.  Truly outstanding!

**Comment by xannor** [comment]
The disconnected error is fine, some cameras just refuse the connection if they cannot validate a renewal or unsub, especially after a reboot or past expire of the sub. I just log a warning so if it does become an issue there is history. 

For the E1, could you enable debugging as per my wiki/logs page and capture the data for the send/receive of it. It could be a preset issue, but since I don't have a device that is true ptz I don't have any data to diagnose with.

**Comment by xannor** [comment]
I more need the actual data from the debug logging, the error just states that it got an invalid response, but I dont know where in the chain of commands the response broke, nor the data/state before that, and I need those to be able to setup a test rig, that can help me diagnose the issue. I dont own an E1 so I need the data of one to test with. You will have to either open the raw log file via terminal or tell the log viewer to load full logs in order to see the DEBUG entries.

**Comment by mikedrews** [comment]
Here are the full logs which I sent before.. (debug still on according to your wiki entry below)
_logger:
   logs:
      async_reolink.rest: debug_


2022-09-21 11:04:48.524 ERROR (MainThread) [custom_components.reolink_rest] Unexpected error fetching reolink_rest-192.168.2.198 data: Subscripted generics cannot be used with class and instance checks
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
return await self.update_method()
File "/config/custom_components/reolink_rest/__init__.py", line 82, in _update_data
return await entity_data.async_update()
File "/config/custom_components/reolink_rest/entity.py", line 475, in async_update
result = await self._execute_commands(commands, command_channel=command_channel)
File "/config/custom_components/reolink_rest/entity.py", line 335, in _execute_commands
or self._process_ptz_responses(
File "/config/custom_components/reolink_rest/entity.py", line 690, in _process_ptz_responses
self.ptz[channel].update_presets(response.presets)
File "/config/custom_components/reolink_rest/entity.py", line 217, in update_presets
if value is not None and not isinstance(value, Mapping[int, ptz.Preset]):
File "/usr/local/lib/python3.10/typing.py", line 994, in __instancecheck__
return self.__subclasscheck__(type(obj))
File "/usr/local/lib/python3.10/typing.py", line 997, in __subclasscheck__
raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
2022-09-21 11:04:48.533 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Living Room' for reolink_rest integration not ready yet: Subscripted generics cannot be used with class and instance checks; Retrying in background
2022-09-21 11:04:53.885 ERROR (MainThread) [custom_components.reolink_rest] Unexpected error fetching reolink_rest-192.168.2.198 data: Subscripted generics cannot be used with class and instance checks
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
return await self.update_method()
File "/config/custom_components/reolink_rest/__init__.py", line 83, in _update_data
return await entity_data.async_update()
File "/config/custom_components/reolink_rest/entity.py", line 475, in async_update
result = await self._execute_commands(commands, command_channel=command_channel)
File "/config/custom_components/reolink_rest/entity.py", line 335, in _execute_commands
or self._process_ptz_responses(
File "/config/custom_components/reolink_rest/entity.py", line 690, in _process_ptz_responses
self.ptz[channel].update_presets(response.presets)
File "/config/custom_components/reolink_rest/entity.py", line 217, in update_presets
if value is not None and not isinstance(value, Mapping[int, ptz.Preset]):
File "/usr/local/lib/python3.10/typing.py", line 994, in __instancecheck__
return self.__subclasscheck__(type(obj))
File "/usr/local/lib/python3.10/typing.py", line 997, in __subclasscheck__
raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks

**Comment by xannor** [comment]
I think your configuration.yaml has a spacing issue, there is no way you would get only errors and no 

DEBUG [xxx.xxx.xxx.xxx]<-[{"cmd":   

style entries. yaml is sensitive about spacing, spaces and tabs do not mix unless you are consistent with the exact mix.
The safest way is to make sure that logger: has no spaces in font of it. the next line logs: should have at least one space, preferably two to make it more visually noticeable, and the line after the async_reolink.rest: debug should have at least one more space than the prior line.

**Comment by mikedrews** [comment]
When I pasted the yaml entry into here the spaces were removed.  I copied the text directly out of your wiki into my yaml file.
I didn't notice the default line in your wiki before. I have now added it and try again.. thanks.

**Comment by mikedrews** [comment]
I'm getting the same error level as I did before..
Here is my yaml entry.  And I did restart.
![image](https://user-images.githubusercontent.com/110789962/191571790-f8f10be2-4d88-4b2b-b178-0affb981fa41.png)

**Comment by xannor** [comment]
you have a space after the default line, logs: should be even with default, otherwise the yaml parser will think it is a sub entry of default:

**Comment by mikedrews** [comment]
Should I be seeing debug information for other integrations?  There is information from all over.

**Comment by xannor** [comment]
Unless you have DEBUG lines for other integrations, no, but you will probably see a bunch with INFO, you can change the default to warning if you want, but I believe info is the normal default, and should not cause issues.

**Comment by mikedrews** [comment]
This entry is causing everything to display debug logging.

![image](https://user-images.githubusercontent.com/110789962/191590758-794066ea-e8ec-4989-845a-5f13502fd0c6.png)

**Comment by mikedrews** [comment]
The camera I am trying to add is 192.168.2.198
[home-assistant.log](https://github.com/xannor/ha_reolink_rest/files/9619864/home-assistant.log)

**Comment by xannor** [comment]
Thankyou for the log. I deleted the entry because you did not scrub the log so I dont want your usernames and passwords part of the history.

**Comment by xannor** [comment]
I published a new release v0.6.7 let me know if this works for you.

**Comment by mikedrews** [comment]
The configuration panel is missing the Pan and Tilt options.
![image](https://user-images.githubusercontent.com/110789962/191605627-bfc81ecf-d58f-4fb7-bc8d-f4c8f656d78d.png)

**Comment by mikedrews** [comment]
I am able to authenticate as admin however there are entities missing for Pan and Tilt and for Auto Focus and Focus.  The camera does have these options.
![image](https://user-images.githubusercontent.com/110789962/191607340-2ce7b600-e5ca-4542-b51e-c96a4c443a21.png)

**Comment by xannor** [comment]
I have not implemented pan or tilt as I dont have a way to test or verify the function would work at this time. Plus the camera API currently only provides a means to pan/tilt, but no way to know the current position, which it does for zoom and focus.

Ill double check in your data but that camera may not support a manual focus or the ability to disable autof focus. I try to rely on the "abilities" the camera says it has as to what controls to build.

**Comment by xannor** [comment]
After some testing, and limited time. I think I am going to put this on hiatus, I would recommend using the built in version as it has fundamentally surpassed what I have built and will have better support than I can provide.
